
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Run pytest and store results
      - run:
          name: Run Tests
          command: |
            pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

      # Generate plots or run Streamlit application briefly for artifacts
      - run:
          name: Generate Plots or Run Streamlit
          command: |
            streamlit run app.py & sleep 60 && curl -I http://localhost:8501

      # Check if files exist before persisting
      - run:
          name: Check for Plot Files
          command: |
            ls -la
            test -f age_balance_scatterplot.html && test -f deposit_countplot.html && test -f job_deposit_barplot.html && test -f marital_deposit_barplot.html

      # Save artifacts
      - persist_to_workspace:
          root: .
          paths:
            - age_balance_scatterplot.html
            - deposit_countplot.html
            - job_deposit_barplot.html
            - marital_deposit_barplot.html

  deploy:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: False
      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t bankapp -t mayank035/bankapp:latest .
            echo $DOCKERHUB_PASSWORD | docker login -u mayank035 --password-stdin
            docker push mayank035/bankapp:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
